Lesson 10: Add web and API auth and profile
KlaysKAS/fefu_backend_2_3 pull request #10
Opened 2021-11-29 04:40 UTC by KlaysKAS

2021-12-03 14:04 UTC, chrn-feip requested changes

2021-12-03 14:04 UTC, chrn-feip commented on app/Http/Controllers/ApiAuthenticationController.php
> +            'name' => ['required', 'regex:/^[-a-zA-Z_0-9]{5,30}$/'],
Тут аналогично по валидации

2021-12-10 13:05 UTC, chrn-feip requested changes

2021-12-10 13:05 UTC, chrn-feip commented on app/Http/Controllers/AuthenticationController.php
> +            if (Auth::attempt($credentials, $request->all()['remember'] == "1")) {
Почему условие на remember? Достаточно проверить Auth::attempt

2021-12-10 13:05 UTC, chrn-feip commented on app/Http/Controllers/ApiAuthenticationController.php
> +        return response()->json(['token' => $token, 'user' => new UserResource($user)], 201);
$token->plainTextToken

2021-12-10 13:05 UTC, chrn-feip commented on app/Http/Controllers/ApiAuthenticationController.php
> +        return response()->json(['token' => $token, 'user' => new UserResource($user)], 201);
$token->plainTextToken

2021-12-10 23:33 UTC, KlaysKAS commented on app/Http/Controllers/AuthenticationController.php
> +            if (Auth::attempt($credentials, $request->all()['remember'] == "1")) {
Это не условие на remember, это если при логине человек хочет, чтобы его запомнили

2021-12-14 15:52 UTC, merged