Lesson 12: Add tests for post and comment controllers
KlaysKAS/fefu_backend_2_3 pull request #12
Opened 2022-01-07 15:01 UTC by KlaysKAS

2022-01-10 14:36 UTC, chrn-feip requested changes

2022-01-10 14:36 UTC, chrn-feip commented on tests/Feature/CommentTest.php
> +        $post = Post::factory()->create();
Здесь пост создаётся без комментов же? Тогда assertJsonStructure, строго говоря, не сработает для пустого списка. Вы в setUp сидером создаёте уже посты и комменты, можно достать из базы пост с whereHas на отношении комментов, чтобы точно был пост с комментариями.

2022-01-10 14:36 UTC, chrn-feip commented on tests/Feature/CommentTest.php
> +            ->assertStatus(200)
А не 404?

2022-01-10 14:36 UTC, chrn-feip commented on tests/Feature/CommentTest.php
> +        $post = Post::query()->where('id', $comment->post_id)->first();
Просто выберите коммент выше с with('post', 'user') (проверьте, что отношения на модели прописаны)

2022-01-10 14:36 UTC, chrn-feip commented on tests/Feature/CommentTest.php
> +        Sanctum::actingAs(User::factory()->create());
Лучше $this->actingAs(..., 'sanctum')->postJson(...)

2022-01-10 14:36 UTC, chrn-feip commented on tests/Feature/CommentTest.php
> +            'role' => '1'
Используйте константу из класса енума, так код легче читать и не надо хардкодить значение по месту применения.

2022-01-10 14:36 UTC, chrn-feip commented on tests/Feature/PostTest.php
> +        $author = User::query()->where('id', $post->user_id)->first();
То же самое про with

2022-01-10 14:36 UTC, chrn-feip commented on tests/Feature/PostTest.php
> +        Sanctum::actingAs(User::factory()->create());
То же самое про actingAs

2022-01-10 14:36 UTC, chrn-feip commented on tests/Feature/PostTest.php
> +        $post = Post::query()->where('id', $comment->post_id)->first();
Post::query()->whereHas('comments'). И тогда не надо отдельно выбирать $comment

2022-01-10 14:36 UTC, chrn-feip commented on tests/Feature/PostTest.php
> +            'role' => '1'
То же самое про константу

2022-01-10 14:38 UTC, chrn-feip commented on tests/Feature/CommentTest.php
> +            ->assertStatus(200)
И тут статус

2022-01-15 05:32 UTC, KlaysKAS commented on tests/Feature/CommentTest.php
> +            ->assertStatus(200)
Приходит  200, но я не до конца понимаю почему именно, разница между найденным комментарием и не найденным в json

2022-01-15 07:43 UTC, KlaysKAS commented on tests/Feature/CommentTest.php
> +            ->assertStatus(200)
Тут та же ситуация, что и выше

2022-01-16 08:35 UTC, chrn-feip commented on tests/Feature/CommentTest.php
> +            ->assertStatus(200)
Проверьте через Postman ваше апи, должно возвращать 404, если в маршрутах прописано missing замыкание. Проверьте, что в методах контроллера параметры Request, Post и Сomment везде указаныи идут в правильном порядке. И аналогично для контроллера постов.

2022-01-16 08:39 UTC, chrn-feip requested changes

2022-01-16 08:39 UTC, chrn-feip commented on tests/Feature/CommentTest.php
> +                'message' => 'No query results for model [App\\Models\\Post] _'
А здесь точно такое сообщение? Что у вас прописано в missing в маршрутах?

2022-01-16 09:03 UTC, chrn-feip commented on tests/Feature/CommentTest.php
> +            ->assertStatus(200)
И запомните: вы тестом описываете ожидаемое поведение. Если ожидается 404, но возвращается 200, значит есть ошибка в коде, который вы тестируете. Не надо код теста подстраивать под фактический результат, это уже не тест.

2022-01-17 02:39 UTC, KlaysKAS commented on tests/Feature/CommentTest.php
> +                'message' => 'No query results for model [App\\Models\\Post] _'
В missing прописаны сообщения 'Post not found', 'Comment not found', как я понял, приложение пытается получить комментарии для несуществующего поста и выбрасывает исключение, отсюда такое сообщение. С моей стороны ошибка, что я указал не совсем честный message

2022-01-17 02:41 UTC, merged