Lesson 7: Add redirecting middleware
KlaysKAS/fefu_backend_2_3 pull request #7
Opened 2021-11-02 09:34 UTC by KlaysKAS

2021-11-04 07:16 UTC, chrn-feip requested changes

2021-11-04 07:16 UTC, chrn-feip commented on app/Http/Middleware/RedirectFromOldSlug.php
> +        $url = substr($url, $posLastSlash + 1);
Посмотрите в сторону других методов $request, которые возвращают URL, кроме url(). Вам нужно избавиться от базового URL (это протокол и домен). Т.е. в оставшейся строке именно для новости должно получиться 'news/<slug>'.

2021-11-04 07:16 UTC, chrn-feip commented on app/Http/Middleware/RedirectFromOldSlug.php
> +            return redirect($baseUrl . "/" . $redirect->new_slug);
Почитайте про редиректы в разделе документации Routes. Он и так редиректит по относительным ссылкам в пределах того же домена.

2021-11-04 07:17 UTC, chrn-feip commented
Не все проверки реализованы для команды

2021-11-11 14:48 UTC, chrn-feip requested changes

2021-11-11 14:48 UTC, chrn-feip commented on app/Console/Commands/ChangeNewsSlug.php
> +        if ($oldSlug === $newUrl) {
Будьте внимательны и тестируйте изменения всегда, вы сравниваете не ту пару значений

2021-11-11 14:48 UTC, chrn-feip commented on app/Console/Commands/ChangeNewsSlug.php
> +        $redirect = Redirect::where('oldSlug', $oldUrl)->where('newSlug', $newUrl);
Где вызов метода в конструкторе, который делает выборку из БД? Вы тестировали эту команду после изменений?

2021-11-11 14:48 UTC, chrn-feip commented on app/Http/Middleware/RedirectFromOldSlug.php
> +            $redirect = Redirect::where('old_slug', $redirect->slug)
1. $redirect->slug? Нет такого поля в модели
2. Где условие на дату?

2021-11-12 02:44 UTC, KlaysKAS commented
Проверка на дату перед присвоением не нужна, т.к. циклы не образуются из-за удаления
`Redirect::where('old_slug',  $newUrl)->delete();`

2021-11-12 05:52 UTC, chrn-feip commented on app/Console/Commands/ChangeNewsSlug.php
> +        $redirect = Redirect::where('oldSlug', $oldUrl)->where('newSlug', $newUrl);
Всё ещё актуально. Где вызов метода first или exists?

2021-11-12 05:53 UTC, chrn-feip commented on app/Console/Commands/ChangeNewsSlug.php
> +        if ($redirect === null) {
Как раз таки <> null (или просто $redirect, если будет exists, которые вернёт boolean) должно быть, потому что вы проверяете существование записи в БД.

2021-11-12 19:34 UTC, merged